### PR TITLE
Add minimal docker image to tun pyth-agent

### PR DESCRIPTION
**Pull request by 146karol**
The purpose of the PR is to add minimal docker image to run pyth-agent while keeping it to be able to build the program.

It was achieved using multi stage process:
- first stage "builder" installs dependencies, gets code and perform build itself,
- second stage installs just runtime dependencies.

Image build from the agent.Dockerfile has size 132 MB, while image build from Dockerfile has size around 5.65GB

### CODE REVIEW

**Comment by jayantk** [comment]
thank you @146karol !

**Review by jayantk — APPROVED** [review]

**Comment by 146karol** [comment]
@jayantk  I added new line at the end of the file. Could you please re-trigger the workflow check?

**Comment by jayantk** [comment]
thanks again! and appreciate you making CI pass -- i was just about to push a commit to this when i realized you already did it.

**Comment by kietng-alpha** [comment]
@jayantk Can we add a minimal tag for this? We would love to use this minimal image without rebuilding it.

**Pull request merged**
